import { UserProfile } from '../types/profile';

export const DEMO_PROFILE_CS: UserProfile = {
  id: 'demo-student-cs-01',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  basic_info: {
    first_name: 'Алекс',
    last_name: 'Садыков',
    age: 16,
    grade: '10',
    target_intake_year: 2027,
    degree_type: 'Bachelor / Undergraduate',
    residence_country: 'Казахстан',
  },
  academics: {
    gpa: 4.85,
    grading_scale: '5.0',
    favorite_subjects: ['Информатика', 'Математика', 'Физика'],
    strong_subjects: ['Алгебра и геометрия', 'Программирование', 'Английский язык'],
    academic_fields: ['Computer Science', 'Artificial Intelligence', 'Software Engineering'],
    intended_major: 'Computer Science',
    alternative_majors: ['Data Science', 'Computer Engineering'],
    performance_level: 'excellent',
  },
  exams: {
    english_level: 'C1',
    ielts: {
      status: 'taken',
      score: '7.0',
      planned_date: '2025-11',
    },
    toefl: {
      status: 'not_taken',
    },
    sat: {
      status: 'planned',
      planned_date: '2026-05',
    },
    act: {
      status: 'not_taken',
    },
    other_exams: 'Школьный олимпиадный тур по информатике',
  },
  extracurriculars: [
    {
      id: 'act-1',
      name: 'Команда робототехники FIRST Robotics / VEX',
      category: 'robotics',
      role: 'Lead Programmer (Python, C++)',
      duration: '2 года (2024–настоящее время)',
      level: 'national',
      achievements: '2-е место на республиканском чемпионате, разработка алгоритма автономного позиционирования.',
    },
    {
      id: 'act-2',
      name: 'Разработка open-source веб-платформы для школьной библиотеки',
      category: 'programming',
      role: 'Full-stack Developer (React, Node.js)',
      duration: '8 месяцев',
      level: 'school',
      achievements: 'Платформой пользуются 650+ учеников школы ежедневно для учета и бронирования книг.',
    },
    {
      id: 'act-3',
      name: 'Волонтерство: обучение младших школьников основам Python',
      category: 'volunteering',
      role: 'Наставник и автор учебных заданий',
      duration: '1.5 года',
      level: 'city',
      achievements: 'Провел более 40 бесплатных занятий для 30 учеников из социально уязвимых семей.',
    },
  ],
  achievements: [
    {
      id: 'ach-1',
      title: 'Диплом II степени на Республиканской олимпиаде по информатике',
      type: 'olympiad' as any,
      issuer: 'Министерство просвещения',
      year: '2025',
      description: 'Среди более 120 финалистов со всей страны в категории 9-10 классов.',
    },
    {
      id: 'ach-2',
      title: 'Победитель регионального хакатона школьных IT-проектов',
      type: 'competition',
      issuer: 'Astana Hub / региональный технопарк',
      year: '2024',
      description: 'Создание прототипа мобильного приложения для сортировки отходов.',
    },
  ],
  preferences: {
    preferred_countries: ['США', 'Германия', 'Нидерланды', 'Южная Корея'],
    excluded_countries: [],
    city_type: 'any',
    campus_type: 'campus',
    climate: 'any',
    instruction_language: 'english_only',
    university_size: 'large',
    focus_orientation: 'research',
  },
  budget: {
    range: '20000_40000',
    max_tuition_usd_year: 25000,
    max_total_usd_year: 35000,
    scholarship_criticality: 'important',
    need_based_aid_ready: true,
    merit_scholarships_ready: true,
    dormitory_needed: true,
  },
  application_preferences: {
    timeline: 'one_year',
    foundation: 'consider',
    financial_aid: 'yes',
    work_during_studies: 'consider',
  },
  constraints: [
    'scholarship_required',
    'dormitory_required',
    'english_taught_only',
  ],
  additional_notes: 'Интересуют вузы с сильными AI/Robotics лабораториями и возможностью бакалаврского ресерча (Undergraduate Research). Готов к подаче на ранние дедлайны (Early Action).',
};

export const DEMO_PROFILE_BUSINESS: UserProfile = {
  id: 'demo-student-biz-02',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  basic_info: {
    first_name: 'Амина',
    last_name: 'Ибраева',
    age: 17,
    grade: '11',
    target_intake_year: 2026,
    degree_type: 'Bachelor / Undergraduate',
    residence_country: 'Казахстан',
  },
  academics: {
    gpa: 4.92,
    grading_scale: '5.0',
    favorite_subjects: ['Экономика', 'Обществознание', 'Английский'],
    strong_subjects: ['Математика', 'Английский', 'История'],
    academic_fields: ['Economics', 'Finance', 'International Business'],
    intended_major: 'Business Administration / Management',
    alternative_majors: ['Economics', 'Finance'],
    performance_level: 'excellent',
  },
  exams: {
    english_level: 'C1',
    ielts: {
      status: 'taken',
      score: '7.5',
      planned_date: '2025-09',
    },
    toefl: {
      status: 'not_taken',
    },
    sat: {
      status: 'not_taken',
    },
    act: {
      status: 'not_taken',
    },
    other_exams: 'Duolingo English Test: 135',
  },
  extracurriculars: [
    {
      id: 'act-biz-1',
      name: 'Школьный клуб Дебатов и Модель ООН (MUN)',
      category: 'leadership',
      role: 'Президент клуба и главный спикер',
      duration: '2.5 года',
      level: 'national',
      achievements: 'Организовал республиканскую конференцию на 180 делегатов, лучший делегат комитета ECOSOC.',
    },
    {
      id: 'act-biz-2',
      name: 'Микро-стартап: эко-товары ручной работы',
      category: 'startup',
      role: 'Ко-фаундер и маркетинг',
      duration: '1 год',
      level: 'city',
      achievements: 'Выручка более $3,000, 15% прибыли передано на посадку деревьев в городском парке.',
    },
  ],
  achievements: [
    {
      id: 'ach-biz-1',
      title: 'Диплом I степени на олимпиаде по экономике и предпринимательству',
      type: 'competition',
      issuer: 'Региональный университет',
      year: '2025',
      description: 'Защита бизнес-плана по развитию локального туризма.',
    },
  ],
  preferences: {
    preferred_countries: ['Италия', 'Германия', 'Нидерланды', 'Венгрия'],
    excluded_countries: [],
    city_type: 'large',
    campus_type: 'urban',
    climate: 'warm',
    instruction_language: 'english_only',
    university_size: 'any',
    focus_orientation: 'career',
  },
  budget: {
    range: '10000_20000',
    max_tuition_usd_year: 12000,
    max_total_usd_year: 20000,
    scholarship_criticality: 'critical',
    need_based_aid_ready: true,
    merit_scholarships_ready: true,
    dormitory_needed: true,
  },
  application_preferences: {
    timeline: 'six_months',
    foundation: 'no',
    financial_aid: 'yes',
    work_during_studies: 'yes',
  },
  constraints: [
    'scholarship_required',
    'low_tuition_priority',
    'schengen_visa_friendly',
  ],
  additional_notes: 'Ищу программы с европейской аккредитацией EQUIS/AACSB и возможностью стажировок во время учебы.',
};
